# Computer Vision Systems and Analysis for Prison Safety {#prison-safety}
#### Keywords
Computer-vision, Prison, Corrections, Safety, Predict, Assault

## The Problem.
Physical and sexual assault run rampant in correctional facilities. In the U.S., approximately 21% of male inmates are physically assaulted during a 6-month period.<sup>1</sup> Further, between 1999 and 2008, roughly 47,500 correctional officers were the victim of an assault or violent act.<sup>2</sup> Prisons are constantly monitored - most facilities already have an extensive CCTV network of cameras in place - but currently prison staff cannot anticipate problems, only react to them. It's no surprise that response times to critical situations can be the difference between life and death in a correctional facility. Prisons take several measures to limit violence including gang research, officer training, and psychological screening; while these measures are critical, they are also expensive and time consuming. While the cat-and-mouse game between officers and inmates may never end, facility managers are always looking for new tools to diminish its prevalence.

## The Solution.
To help solve the problem, we can leverage recent advancements in computer vision to further monitor, prevent, and predict potential violence in prisons. Detection systems can alert prison staff to respond to problems as they occur and learn behaviors that may be predictive of impending incidents.  In real time, computer-vision algorithms can detect inmates' faces, heart rates, gestures, behavioral patterns, and identify suspicious movements. Since individuals can be detected and tracked, so too can groups. A social network can be constructed to identify gangs and detect large gatherings of members.

In an analytical setting, correctional facility administrators can later utilize the spatially-mapped data to optimize prison layouts and staff locations while identifying and reducing blind-spots for further preventative measures. Specifically, patterns will emerge over time around when and where certain behavior occurs, where staffing weaknesses arise, and where "hot spots" tend to cluster; this data can be used to influence existing and future architectural decisions and optimize staff rotations.

A simple rollout of our software on top of the existing CCTV infrastructure will come complete with a new dashboard, computer vision algorithms, alerts, and spatial mapping abilities and analysis. Facility managers and officers will be trained to use all aspects of the program. Similar use of computer vision has been applied in areas with extensive surveillance already in place, like casinos and airports. Although the technology is still nascent, success in these adjacent industries proves the project's viability.

## Moving Forward.
The use of this technology will have a positive impact on increasing productivity of prison staff while reducing prison violence and misconduct. Indirect economic benefits will also arise: a safer prison environment translates to reduced medical costs, less officer turnover, and reduced hiring/training costs. 

As this technology proliferates through correctional facilities, privacy concerns may arise in the general public, since only a few simple tweaks would be necessary to move these surveillance systems out into city streets. Even in a correctional facility (where privacy is already limited) it is paramount that we engage in debate to understand the extent to which inmates, officers, and the public feel the technology should be utilized. The outcome of these discussions can pave the way for proper management of a computer vision system which can dramatically help minimize costs and reduce prison violence, helping to ensure the safety of all.

**References:**

<sup>1</sup>Contextualization of Physical and Sexual Assault in Male Prisons: Incidents and Their Aftermath, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2811042/

<sup>2</sup>U.S. Correctional Officers Killed or Injured on the Job http://www.aca.org/ACA_PROD_IMIS/Docs/Corrections%20Today/2013%20Articles/November%20Articles/Research%20Notes.pdf
